# 广告
type lcNews {
   id:ID          
   Images: [File]
   title:String   
   content:String   
   isValid:Boolean  
   updateAt:Date
   createAt:Date
}

extend type Query{
    # 查询所有广告
    getlcNews:[lcNews]
    # 根据ID查找广告
    getlcNewsById(id:String):lcNews
    # 分页查找
    getlcNewsPage(pageIndex: Int, pageSize: Int,lcnews:searchlcNews): [lcNews]
    # 查找分页总数
    getlcNewsCount(lcnews:searchlcNews):Int
    # 根据条件查找
    getlcNewsWhere(lcnews:searchlcNews): [lcNews]    
}

extend type Mutation{
    # 添加修改广告
    savelcNews(lcnews:inputlcNews):lcNews
    # 删除广告
    deletelcNews(id:String):Boolean
}

input inputlcNews{ 
   id:String   
   imageIds: [String]
   title:String   
   content:String     
   isValid:Boolean       
}

input searchlcNews{
    id:Json
    title:Json    
}