# 广告
type Menul {
   id:ID  
   name1:String
   name2:String
   name3:String
   name4:String
   name5:String
   name6:String
   name7:String
   updateAt:Date
   createAt:Date
}

extend type Query{
    # 查询所有文章
    getMenul:[Menul]
    # 根据ID查找文章
    getMenulById(id:String):Menul       
}

extend type Mutation{
    # 添加修改文章
    saveMenul(menul:inputMenul):Menul
    # 删除文章
    deleteMenul(id:String):Boolean
}

input inputMenul{ 
   id:String         
   name1:String
   name2:String
   name3:String
   name4:String
   name5:String
   name6:String
   name7:String 
}

