# 广告
type ContactInfo {
   id:ID  
   comName1:String 
   comName2:String   
   sPhone:String     
   webName:String
   comAddress:String
   cPhone1:String
   cPhone2:String
   webSite:String
   updateAt:Date
   createAt:Date
}

extend type Query{
    # 查询所有文章
    getContactInfo:[ContactInfo]
    # 根据ID查找文章
    getContactInfoById(id:String):ContactInfo       
}

extend type Mutation{
    # 添加修改文章
    saveContactInfo(contactInfo:inputContactInfo):ContactInfo
    # 删除文章
    deleteContactInfo(id:String):Boolean
}

input inputContactInfo{ 
   id:String         
   comName1:String 
   comName2:String    
   sPhone:String     
   webName:String
   comAddress:String
   cPhone1:String
   cPhone2:String
   webSite:String   
}

